### ISSUE TITLE
ERR_REQUIRE_ESM error when using commonjs to compile

### ISSUE THREAD

**Issue by raintreasure** [Web3Auth/web3auth-wagmi-connector#46]
My project is using commonjs to compile, and will report following error, it seems correctly fetch web3authWagmiConnector.cjs.js, but  when  web3authWagmiConnector.cjs.js using require to fetch ESM module, compiler complains.

so can you change require to import in cjs file? It should works. Or is there a workaround?

error - Error [ERR_REQUIRE_ESM]: require() of ES Module  ...\node_modules\@web3auth\web3auth-wagmi-connector\node_modules\@wagmi\core\dist\index.js from ...\node_modules\@web3auth\web3auth-wagmi-connector\dist\web3authWagmiConnector.cjs.js not supported.
Instead change the require of index.js in ...\node_modules\@web3auth\web3auth-wagmi-connector\dist\web3authWagmiConnector.cjs.js to a dynamic import() which is available in all CommonJS modules.
    at 915 (...\node_modules\@web3auth\web3auth-wagmi-connector\dist\web3authWagmiConnector.cjs.js:18:30)
    at __webpack_require__ (...\node_modules\@web3auth\web3auth-wagmi-connector\dist\web3authWagmiConnector.cjs.js:236:41)
    at ...\node_modules\@web3auth\web3auth-wagmi-connector\dist\web3authWagmiConnector.cjs.js:292:72
    at ...\node_modules\@web3auth\web3auth-wagmi-connector\dist\web3authWagmiConnector.cjs.js:300:3
    at Object.<anonymous> (...\node_modules\@web3auth\web3auth-wagmi-connector\dist\web3authWagmiConnector.cjs.js:303:12)
    at @web3auth/web3auth-wagmi-connector (...\.next\server\pages\_app.js:329:18)
    at __webpack_require__ (...\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_app.tsx:22:93)
    at __webpack_require__.a (...\.next\server\webpack-runtime.js:97:13)
    at eval (webpack-internal:///./pages/_app.tsx:1:21)
    at ./pages/_app.tsx (...\.next\server\pages\_app.js:264:1)
    at __webpack_require__ (...\.next\server\webpack-runtime.js:33:42)
    at __webpack_exec__ (...\.next\server\pages\_app.js:482:39)
    at ...\.next\server\pages\_app.js:483:28
    at Object.<anonymous> (...\.next\server\pages\_app.js:486:3)
    at Object.requirePage (...\node_modules\next\dist\server\require.js:58:12)
    at ...\node_modules\next\dist\server\load-components.js:57:54
    at async Promise.all (index 1)
    at async Object.loadComponents (...\node_modules\next\dist\server\load-components.js:55:33)
    at async DevServer.findPageComponents (...\node_modules\next\dist\server\next-server.js:545:36) {
  code: 'ERR_REQUIRE_ESM',
  page: '/'
}

**Comment by EmanueleBordoni** [comment]
I have the same problem

**Comment by EmanueleBordoni** [comment]
Have you solved this?

**Comment by chaitanyapotti** [comment]
Fixed in 3.0.0

**Comment by EmanueleBordoni** [comment]
> Fixed in 3.0.0

Ok, but now I have this error:
`Uncaught Error: Cannot find module '/path/node_modules/ethers/lib/utils' imported from /path/node_modules/@web3auth/web3auth-wagmi-connector/dist/web3authWagmiConnector.esm.js
Did you mean to import ethers/lib/utils.js?`

**Comment by sk25649** [comment]
> > Fixed in 3.0.0
> 
> Ok, but now I have this error: `Uncaught Error: Cannot find module '/path/node_modules/ethers/lib/utils' imported from /path/node_modules/@web3auth/web3auth-wagmi-connector/dist/web3authWagmiConnector.esm.js Did you mean to import ethers/lib/utils.js?`

I am seeing the same issue

**Comment by tech-openmeme** [comment]
> Fixed in 3.0.0



> > Fixed in 3.0.0
> 
> Ok, but now I have this error: `Uncaught Error: Cannot find module '/path/node_modules/ethers/lib/utils' imported from /path/node_modules/@web3auth/web3auth-wagmi-connector/dist/web3authWagmiConnector.esm.js Did you mean to import ethers/lib/utils.js?`

The same issue occurs for me.
